#!/usr/bin/env Rscript

args <- commandArgs(trailingOnly = TRUE)

if (length(args) != 3) {
  stop("Please provide exactly three arguments: path_output, file_penncnv, and sample_map")
}

path_output    <- args[1]
file_penncnv   <- args[2]
sample_map     <- args[3]

## Sample_Map.txt can be generated along with final report from Genome Studio
## used to check Sample_ID in the CNV results generated by individual methods

suppressMessages({
  require(data.table)
})

## selected columns from CNV results
col_sel <- c("chr", "posStart", "posEnd", "CN", "Sample_ID", "conf", 
             "numSNP", "avgConf", "length", "CNV_type", "method")

sample <- tryCatch({
  read.delim(file = sample_map, as.is = TRUE)
}, error = function(e) {
  stop("Error reading sample map: ", e$message)
})

# Read and process PennCNV data ------------------------------------------------
read_pcnv <- function(file_pcnv, col_sel, sample) {
  cat("Read in CNV calls from PennCNV ...\n")
  tryCatch({
    dat <- read.table(file = file_pcnv, sep = "\t", check.names = FALSE,
                      header = FALSE, stringsAsFactors = FALSE, 
                      comment.char = "")
    names(dat) <- c("chr", "posStart", "posEnd", "CN", "Sample_ID", "snpStart", "snpEnd", "conf", "numSNP")
    dat$Sample_ID <- gsub("\\.txt", "", dat$Sample_ID)
    dat$length <- dat$posEnd - dat$posStart + 1
    dat$avgConf <- dat$conf/dat$numSNP
    
    dat <- subset(dat, chr %in% c(1:26) & CN != 2)
    dat$CNV_type <- ifelse(dat$CN > 2, "Gain", "Loss")
    dat$method <- "PennCNV"
    dat$CN[which(dat$CN >= 3)] <- 3 ## set CN >= 3 to CN = 3
    
    if (!all(dat$Sample_ID %in% sample$Sample_ID)) {
      mismatched_ids <- dat$Sample_ID[!dat$Sample_ID %in% sample$Sample_ID]
      warning("The following sample IDs are not found in the sample map: ", paste(mismatched_ids, collapse = ", "))
    }
    
    return(dat[, col_sel])
  }, error = function(e) {
    warning("Failed to read or process CNV data: ", e$message)
    return(data.frame())
  })
}

dat_penncnv <- read_pcnv(file_pcnv = file_penncnv, col_sel = col_sel, sample = sample)

if (nrow(dat_penncnv) > 0) {
  write.table(dat_penncnv, 
              file = file.path(path_output, "cnv.penncnv.txt"),
              quote = FALSE, row.names = FALSE, sep = "\t")
} else {
  cat("No data to write; check the warnings for details.\n")
}